server:
  port: 9999
spring:
  profiles:
#    active: dev
    active: @profileActive@

#自动更新配置
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#    enabled-by-default: true
#  metrics:
#    tags:
#      application: ${spring.application.name}
#      environment: ${spring.profiles}
#  endpoint:
    health:
      show-details: always    #详细的应用健康信息

eurekaServer:
  port: defaultPort
feign:
  client:
    provide:
      name: defaultName
      path: defaultPath
